#!/usr/bin/env bash
# Shared environment setup for all training scripts in this repo.
# Source this file at the top of every entry-point script.

set -euo pipefail

# Locate project paths.
INGPO_ROOT="${INGPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

# PYTHONPATH: project root so `treetune` and `guidance` packages resolve.
export PYTHONPATH="${INGPO_ROOT}:${PYTHONPATH:-}"

# Jsonnet `import` resolves under the unified configs/ tree.
export APP_JSONNET_PATH="${INGPO_ROOT}/configs:${INGPO_ROOT}"

# Standard env vars (kept compatible with upstream SPO conventions).
export APP_SEED="${APP_SEED:-42}"
export MASTER_PORT="${MASTER_PORT:-$(python3 -c "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.bind(('', 0)); print(s.getsockname()[1]); s.close()")}"
export APP_DIRECTORY="${APP_DIRECTORY:-${INGPO_ROOT}/experiments}"
export APP_MINIMIZE_STORED_FILES="${APP_MINIMIZE_STORED_FILES:-True}"
export WANDB_PROJECT="${WANDB_PROJECT:-treetune}"
mkdir -p "${APP_DIRECTORY}"

# Default GPU is index 0; override with INGPO_GPU=N.
INGPO_GPU="${INGPO_GPU:-0}"

# Helpers ---------------------------------------------------------------------
# Run training with `--configs A,B,C`.  Algorithm selection is purely from the
# chained configs; the unified entry point is `treetune.main` (InGPO is
# auto-registered when `treetune` is imported).
#
# Usage: ingpo_run "<exp_name>" "configs/foo.jsonnet,configs/bar.jsonnet" [extra args]
ingpo_run() {
  local exp_name="$1"; shift
  local cfgs="$1"; shift
  WANDB_PROJECT="${WANDB_PROJECT}" \
  APP_EXPERIMENT_NAME="${exp_name}" \
  deepspeed --master_port "${MASTER_PORT}" --include "localhost:${INGPO_GPU}" \
    -m treetune.main \
    --configs "${cfgs},${INGPO_ROOT}/configs/gpus/gpu_${INGPO_GPU}.jsonnet" \
    "$@" \
    run_iteration_loop
}

ingpo_eval() {
  local exp_name="$1"; shift
  local cfgs="$1"; shift
  local last_policy="$1"; shift
  WANDB_PROJECT="${WANDB_PROJECT}" \
  APP_EXPERIMENT_NAME="${exp_name}" \
  deepspeed --master_port "${MASTER_PORT}" --include "localhost:${INGPO_GPU}" \
    -m treetune.main \
    --configs "${cfgs},${INGPO_ROOT}/configs/gpus/gpu_${INGPO_GPU}.jsonnet" \
    "$@" \
    evaluate --iteration 0 --last_policy_path "${last_policy}"
}

# ensure_tree_config <shape>
# Resolve a tree shape (e.g. "666", "6666", "3456", "8888") to a jsonnet
# overlay path.  If a checked-in config exists under
#   configs/episode_generators/branch_factor_<shape>.jsonnet
# we use it as-is.  Otherwise we auto-generate one under
#   configs/episode_generators/_generated/branch_factor_<shape>.jsonnet
# so any shape works without hand-editing the repo.
#
# Shape is a string of digits 1-9, one digit per depth level (the i-th
# digit is the branch factor at depth i).  M (per-segment token cap)
# defaults by depth: <=3 -> 600, 4 -> 500, 5 -> 400, >=6 -> 300.  Override
# with TREE_M=<int>.
#
# Prints the resolved overlay path on stdout.
ensure_tree_config() {
  local shape="$1"
  local checked_in="${INGPO_ROOT}/configs/episode_generators/branch_factor_${shape}.jsonnet"
  if [[ -f "${checked_in}" ]]; then
    echo "${checked_in}"
    return 0
  fi

  if ! [[ "${shape}" =~ ^[1-9]+$ ]]; then
    echo "[tree] invalid tree shape '${shape}': must be a string of digits 1-9 (e.g. 666, 3456)" >&2
    return 1
  fi

  local gen_dir="${INGPO_ROOT}/configs/episode_generators/_generated"
  local out="${gen_dir}/branch_factor_${shape}.jsonnet"
  if [[ -f "${out}" ]]; then
    echo "${out}"
    return 0
  fi

  mkdir -p "${gen_dir}"
  local depth=${#shape}
  local M="${TREE_M:-}"
  if [[ -z "${M}" ]]; then
    if   [[ ${depth} -le 3 ]]; then M=600
    elif [[ ${depth} -eq 4 ]]; then M=500
    elif [[ ${depth} -eq 5 ]]; then M=400
    else                            M=300
    fi
  fi

  {
    echo "// Auto-generated by scripts/_common.sh:ensure_tree_config."
    echo "// Shape='${shape}' depth=${depth} M=${M}."
    echo "// Override M by setting TREE_M=<int> before invoking the training script."
    echo "{"
    echo "  episode_generator+: {"
    echo "    inference_strategy+: {"
    echo "      M: ${M},"
    echo "      max_depth: ${depth},"
    echo "      branch_factor_strategy+: {"
    echo "        branch_factors: ["
    local i
    for (( i=0; i<depth; i++ )); do
      echo "          { depth: ${i}, branch_factor: ${shape:$i:1} },"
    done
    echo "        ],"
    echo "      },"
    echo "    },"
    echo "  },"
    echo "}"
  } > "${out}"

  echo "[tree] generated branch_factor_${shape}.jsonnet (depth=${depth}, M=${M})" >&2
  echo "${out}"
}

default_model_base_for_suffix() {
  local suffix="$1"
  case "${suffix}" in
    ingpo_tree|spo_tree|spo_chain|grpo)
      echo "qwen1_5b_base"
      ;;
    ppo|dpo_positive|restem)
      echo "rho1bSft2"
      ;;
    *)
      echo "qwen1_5b_base"
      ;;
  esac
}

# resolve_math_config <suffix> <model_alias>
# First prefer a fully materialized config:
#   configs/polIter_<model_alias>_<suffix>_MATH.jsonnet
# If it does not exist but configs/model_overrides/<model_alias>.jsonnet does,
# compose a known base config with that model override. This keeps new model
# support compact while preserving existing hand-tuned configs.
resolve_math_config() {
  local suffix="$1"
  local model="$2"
  local direct="${INGPO_ROOT}/configs/polIter_${model}_${suffix}_MATH.jsonnet"
  if [[ -f "${direct}" ]]; then
    echo "${direct}"
    return 0
  fi

  local override="${INGPO_ROOT}/configs/model_overrides/${model}.jsonnet"
  if [[ -f "${override}" ]]; then
    local base="${MODEL_BASE:-$(default_model_base_for_suffix "${suffix}")}"
    local base_cfg="${INGPO_ROOT}/configs/polIter_${base}_${suffix}_MATH.jsonnet"
    if [[ ! -f "${base_cfg}" ]]; then
      echo "[model] missing base config for MODEL=${model}: ${base_cfg}" >&2
      return 1
    fi
    echo "${base_cfg},${override}"
    return 0
  fi

  echo "[model] unknown MODEL=${model}; expected ${direct} or ${override}" >&2
  return 1
}
