#!/usr/bin/env bash
# Shared environment setup for all training scripts in this repo.
# Source this file at the top of every entry-point script.

set -euo pipefail

# Locate project paths.
INGPO_ROOT="${INGPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

# PYTHONPATH: project root so `treetune` and `guidance` packages resolve.
export PYTHONPATH="${INGPO_ROOT}:${PYTHONPATH:-}"

# Jsonnet `import` resolves under the unified configs/ tree.
export APP_JSONNET_PATH="${INGPO_ROOT}/configs:${INGPO_ROOT}"

# Standard env vars (kept compatible with upstream SPO conventions).
export APP_SEED="${APP_SEED:-42}"
export MASTER_PORT="${MASTER_PORT:-$(python3 -c "import socket; s=socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.bind(('', 0)); print(s.getsockname()[1]); s.close()")}"
export APP_DIRECTORY="${APP_DIRECTORY:-${INGPO_ROOT}/experiments}"
export APP_MINIMIZE_STORED_FILES="${APP_MINIMIZE_STORED_FILES:-True}"
export WANDB_PROJECT="${WANDB_PROJECT:-treetune}"
mkdir -p "${APP_DIRECTORY}"

# Default GPU is index 0; override with INGPO_GPU=N or INGPO_GPUS=0,1,2,3.
# With INGPO_GPUS, Deepspeed launches one process per listed GPU.  Episode
# generation is sharded by process, so each rank can host its own vLLM server.
INGPO_GPU_INCLUDE="${INGPO_GPUS:-${INGPO_GPU:-0}}"
INGPO_FIRST_GPU="${INGPO_GPU_INCLUDE%%,*}"

# Helpers ---------------------------------------------------------------------
jsonnet_value() {
  local value="$1"
  case "${value}" in
    auto)
      echo "'auto'"
      ;;
    true|false|null)
      echo "${value}"
      ;;
    *)
      echo "${value}"
      ;;
  esac
}

ensure_gpu_config() {
  local first_gpu="$1"
  local eval_gpu="${INGPO_EVALUATE_GPU:-${first_gpu}}"
  local vllm_gpu_offset="${INGPO_VLLM_GPU_OFFSET:-${first_gpu}}"
  local gen_dir="${APP_DIRECTORY}/_generated_configs/gpus"
  local out="${gen_dir}/gpu_${first_gpu}_eval_${eval_gpu}_vllm_offset_${vllm_gpu_offset}.jsonnet"

  mkdir -p "${gen_dir}"
  cat > "${out}" <<EOF
// Auto-generated by scripts/_common.sh:ensure_gpu_config.
// Deepspeed include: localhost:${INGPO_GPU_INCLUDE}
// Set INGPO_VLLM_GPU_OFFSET to put generation vLLM servers on another GPU block.
{
  evaluate_gpu: ${eval_gpu},
  episode_generator+: {
    gpu_offset: ${vllm_gpu_offset},
  },
}
EOF
  echo "${out}"
}

ensure_runtime_config() {
  if [[ "${INGPO_FAST_OVERLAY:-1}" == "0" ]]; then
    return 0
  fi

  local gen_dir="${APP_DIRECTORY}/_generated_configs/runtime_overrides"
  local out="${gen_dir}/short_run_fast_runtime.jsonnet"

  local eval_every="${INGPO_EVAL_EVERY_N_ITERATIONS:-1000}"
  local save_steps="${INGPO_SAVE_STEPS:-1}"
  local keep_steps="${INGPO_CHECKPOINT_KEEP_STEPS:-1}"
  local target_train_batch_size="${INGPO_TARGET_TRAIN_BATCH_SIZE:-128}"
  local gradient_accumulation_steps="${INGPO_GRADIENT_ACCUMULATION_STEPS:-null}"
  local per_device_train_batch_size="${INGPO_PER_DEVICE_TRAIN_BATCH_SIZE:-2}"
  if [[ "${gradient_accumulation_steps}" != "null" && -z "${INGPO_PER_DEVICE_TRAIN_BATCH_SIZE:-}" ]]; then
    per_device_train_batch_size="null"
  fi
  local per_device_eval_batch_size="${INGPO_PER_DEVICE_EVAL_BATCH_SIZE:-2}"
  local num_epochs_per_iteration="${INGPO_NUM_EPOCHS_PER_ITERATION:-1}"
  local num_episodes_per_iteration="${INGPO_NUM_EPISODES_PER_ITERATION:-null}"
  local dataset_num_samples_per_iteration="${INGPO_DATASET_NUM_SAMPLES_PER_ITERATION:-null}"
  local total_num_iterations="${INGPO_TOTAL_NUM_ITERATIONS:-null}"
  local vllm_gpu_mem
  vllm_gpu_mem="$(jsonnet_value "${INGPO_VLLM_GPU_MEMORY_UTILIZATION:-auto}")"
  local vllm_min_free="${INGPO_VLLM_MIN_AVAILABLE_GPU_MEMORY_MB:-1024}"
  local max_programs="${INGPO_MAX_CONCURRENT_PROGRAMS:-256}"
  local max_generations="${INGPO_MAX_CONCURRENT_GENERATIONS:-256}"
  local value_max_programs="${INGPO_VALUE_MAX_CONCURRENT_PROGRAMS:-512}"
  local value_max_generations="${INGPO_VALUE_MAX_CONCURRENT_GENERATIONS:-512}"
  local vllm_max_num_seqs="${INGPO_VLLM_MAX_NUM_SEQS:-1024}"
  local vllm_swap_space="${INGPO_VLLM_SWAP_SPACE:-32}"
  local ingpo_score_concurrency="${INGPO_SCORE_CONCURRENCY:-64}"
  local ingpo_K="${INGPO_K:-null}"
  local ingpo_m="${INGPO_M:-null}"
  local ingpo_share_pair_budget_fraction="${INGPO_SHARE_PAIR_BUDGET_FRACTION:-null}"

  mkdir -p "${gen_dir}"
  cat > "${out}" <<EOF
// Auto-generated by scripts/_common.sh:ensure_runtime_config.
// Short-run defaults favor throughput and checkpoint resumability.
// Disable this overlay with INGPO_FAST_OVERLAY=0.
// Speed-related env vars:
//   INGPO_GPUS=0,1,2,3
//   INGPO_VLLM_GPU_OFFSET=4
//   INGPO_TARGET_TRAIN_BATCH_SIZE=${target_train_batch_size}
//   INGPO_PER_DEVICE_TRAIN_BATCH_SIZE=${per_device_train_batch_size}
//   INGPO_GRADIENT_ACCUMULATION_STEPS=${gradient_accumulation_steps}
//   INGPO_NUM_EPISODES_PER_ITERATION=${num_episodes_per_iteration}
//   INGPO_DATASET_NUM_SAMPLES_PER_ITERATION=${dataset_num_samples_per_iteration}
//   INGPO_MAX_CONCURRENT_PROGRAMS=${max_programs}
//   INGPO_MAX_CONCURRENT_GENERATIONS=${max_generations}
//   INGPO_SCORE_CONCURRENCY=${ingpo_score_concurrency}
//   INGPO_VLLM_GPU_MEMORY_UTILIZATION=${INGPO_VLLM_GPU_MEMORY_UTILIZATION:-auto}
{
  evaluate_every_n_iterations: ${eval_every},
  num_episodes_per_iteration: if ${num_episodes_per_iteration} == null then super.num_episodes_per_iteration else ${num_episodes_per_iteration},
  num_iterations: if ${total_num_iterations} == null then super.num_iterations else ${total_num_iterations},
  episode_generator+: {
    dataset_num_samples_per_iteration: if ${dataset_num_samples_per_iteration} == null then super.dataset_num_samples_per_iteration else ${dataset_num_samples_per_iteration},
    total_num_iterations: if ${total_num_iterations} == null then super.total_num_iterations else ${total_num_iterations},
    vllm_gpu_memory_utilization: ${vllm_gpu_mem},
    vllm_min_available_gpu_memory_mb: ${vllm_min_free},
    inference_strategy+: {
      max_concurrent_programs: ${max_programs},
      max_concurrent_generations: ${max_generations},
      ingpo_score_concurrency: ${ingpo_score_concurrency},
      ingpo_K: if ${ingpo_K} == null then super.ingpo_K else ${ingpo_K},
      ingpo_m: if ${ingpo_m} == null then super.ingpo_m else ${ingpo_m},
      ingpo_share_pair_budget_fraction: if ${ingpo_share_pair_budget_fraction} == null then super.ingpo_share_pair_budget_fraction else ${ingpo_share_pair_budget_fraction},
    },
    value_estimation_inference_strategy+: {
      max_concurrent_programs: ${value_max_programs},
      max_concurrent_generations: ${value_max_generations},
    },
    vllm_server+: {
      swap_space: ${vllm_swap_space},
      max_num_seqs: ${vllm_max_num_seqs},
      enable_prefix_caching: true,
    },
  },
  trainer+: {
    num_epochs_per_iteration: ${num_epochs_per_iteration},
    general_training_args+: {
      target_train_batch_size: ${target_train_batch_size},
      per_device_train_batch_size: ${per_device_train_batch_size},
      per_device_eval_batch_size: ${per_device_eval_batch_size},
      gradient_accumulation_steps: ${gradient_accumulation_steps},
      save_steps: ${save_steps},
      checkpoint_keep_steps: ${keep_steps},
    },
  },
}
EOF
  echo "${out}"
}

# Run training with `--configs A,B,C`.  Algorithm selection is purely from the
# chained configs; the unified entry point is `treetune.main` (InGPO is
# auto-registered when `treetune` is imported).
#
# Usage: ingpo_run "<exp_name>" "configs/foo.jsonnet,configs/bar.jsonnet" [extra args]
ingpo_run() {
  local exp_name="$1"; shift
  local cfgs="$1"; shift
  local gpu_config runtime_config resolved_cfgs
  gpu_config="$(ensure_gpu_config "${INGPO_FIRST_GPU}")"
  runtime_config="$(ensure_runtime_config)"
  resolved_cfgs="${cfgs},${gpu_config}"
  if [[ -n "${runtime_config}" ]]; then
    resolved_cfgs+=",${runtime_config}"
  fi
  WANDB_PROJECT="${WANDB_PROJECT}" \
  APP_EXPERIMENT_NAME="${exp_name}" \
  deepspeed --master_port "${MASTER_PORT}" --include "localhost:${INGPO_GPU_INCLUDE}" \
    "${INGPO_ROOT}/treetune/main.py" \
    --configs "${resolved_cfgs}" \
    "$@" \
    run_iteration_loop
}

ingpo_eval() {
  local exp_name="$1"; shift
  local cfgs="$1"; shift
  local last_policy="$1"; shift
  local gpu_config
  gpu_config="$(ensure_gpu_config "${INGPO_FIRST_GPU}")"
  WANDB_PROJECT="${WANDB_PROJECT}" \
  APP_EXPERIMENT_NAME="${exp_name}" \
  deepspeed --master_port "${MASTER_PORT}" --include "localhost:${INGPO_GPU_INCLUDE}" \
    "${INGPO_ROOT}/treetune/main.py" \
    --configs "${cfgs},${gpu_config}" \
    "$@" \
    evaluate --iteration 0 --last_policy_path "${last_policy}"
}

# ensure_tree_config <shape>
# Resolve a tree shape (e.g. "666", "6666", "3456", "8888") to a jsonnet
# overlay path.  If a checked-in config exists under
#   configs/episode_generators/branch_factor_<shape>.jsonnet
# we use it as-is.  Otherwise we auto-generate one under
#   configs/episode_generators/_generated/branch_factor_<shape>.jsonnet
# so any shape works without hand-editing the repo.
#
# Shape is a string of digits 1-9, one digit per depth level (the i-th
# digit is the branch factor at depth i).  M (per-segment token cap)
# defaults by depth: <=3 -> 600, 4 -> 500, 5 -> 400, >=6 -> 300.  Override
# with TREE_M=<int>.
#
# Prints the resolved overlay path on stdout.
ensure_tree_config() {
  local shape="$1"
  local checked_in="${INGPO_ROOT}/configs/episode_generators/branch_factor_${shape}.jsonnet"
  if [[ -f "${checked_in}" ]]; then
    echo "${checked_in}"
    return 0
  fi

  if ! [[ "${shape}" =~ ^[1-9]+$ ]]; then
    echo "[tree] invalid tree shape '${shape}': must be a string of digits 1-9 (e.g. 666, 3456)" >&2
    return 1
  fi

  local gen_dir="${INGPO_ROOT}/configs/episode_generators/_generated"
  local out="${gen_dir}/branch_factor_${shape}.jsonnet"
  if [[ -f "${out}" ]]; then
    echo "${out}"
    return 0
  fi

  mkdir -p "${gen_dir}"
  local depth=${#shape}
  local M="${TREE_M:-}"
  if [[ -z "${M}" ]]; then
    if   [[ ${depth} -le 3 ]]; then M=600
    elif [[ ${depth} -eq 4 ]]; then M=500
    elif [[ ${depth} -eq 5 ]]; then M=400
    else                            M=300
    fi
  fi

  {
    echo "// Auto-generated by scripts/_common.sh:ensure_tree_config."
    echo "// Shape='${shape}' depth=${depth} M=${M}."
    echo "// Override M by setting TREE_M=<int> before invoking the training script."
    echo "{"
    echo "  episode_generator+: {"
    echo "    inference_strategy+: {"
    echo "      M: ${M},"
    echo "      max_depth: ${depth},"
    echo "      branch_factor_strategy+: {"
    echo "        branch_factors: ["
    local i
    for (( i=0; i<depth; i++ )); do
      echo "          { depth: ${i}, branch_factor: ${shape:$i:1} },"
    done
    echo "        ],"
    echo "      },"
    echo "    },"
    echo "  },"
    echo "}"
  } > "${out}"

  echo "[tree] generated branch_factor_${shape}.jsonnet (depth=${depth}, M=${M})" >&2
  echo "${out}"
}

default_model_base_for_suffix() {
  local suffix="$1"
  case "${suffix}" in
    ingpo_tree|spo_tree|spo_chain|grpo)
      echo "qwen1_5b_base"
      ;;
    ppo|dpo_positive|restem)
      echo "rho1bSft2"
      ;;
    *)
      echo "qwen1_5b_base"
      ;;
  esac
}

# resolve_math_config <suffix> <model_alias>
# First prefer a fully materialized config:
#   configs/polIter_<model_alias>_<suffix>_MATH.jsonnet
# If it does not exist but configs/model_overrides/<model_alias>.jsonnet does,
# compose a known base config with that model override. This keeps new model
# support compact while preserving existing hand-tuned configs.
resolve_math_config() {
  local suffix="$1"
  local model="$2"
  local direct="${INGPO_ROOT}/configs/polIter_${model}_${suffix}_MATH.jsonnet"
  if [[ -f "${direct}" ]]; then
    echo "${direct}"
    return 0
  fi

  local override="${INGPO_ROOT}/configs/model_overrides/${model}.jsonnet"
  if [[ -f "${override}" ]]; then
    local base="${MODEL_BASE:-$(default_model_base_for_suffix "${suffix}")}"
    local base_cfg="${INGPO_ROOT}/configs/polIter_${base}_${suffix}_MATH.jsonnet"
    if [[ ! -f "${base_cfg}" ]]; then
      echo "[model] missing base config for MODEL=${model}: ${base_cfg}" >&2
      return 1
    fi
    echo "${base_cfg},${override}"
    return 0
  fi

  echo "[model] unknown MODEL=${model}; expected ${direct} or ${override}" >&2
  return 1
}
